---
title       : Developing Data Products
subtitle    : (Use arrow keys to navigate)
author      : Nguyen Toan
job         : from Data Science course on Coursera
framework   : io2012
highlighter : highlight.js
hitheme     : tomorrow
url:
  lib: ../../libraries
  assets: ../../assets
---
```{r setup, cache = F, echo = F, message = F, warning = F, tidy = F, results='hide'}
# make this an external chunk that can be included in any file
library(knitr)
options(width = 100)
opts_chunk$set(message = F, error = F, warning = F, comment = NA, fig.align = 'center', dpi = 100, tidy = F, cache.path = '.cache/', fig.path = 'fig/')

options(xtable.type = 'html')
knit_hooks$set(inline = function(x) {
  if(is.numeric(x)) {
    round(x, getOption('digits'))
  } else {
    paste(as.character(x), collapse = ', ')
  }
})
knit_hooks$set(plot = knitr:::hook_plot_html)
runif(1)
```

## About these slides
- This is the documentation on the *BMI Calculator* Shinyapp, which is a project from *Developing Data Products* course on Coursera.
- This was created using [slidify](http://ramnathv.github.io/slidify/)

## What is BMI

- The body mass index (BMI), or Quetelet index, is a measure of relative weight based on an individual's mass and height.

- Devised between 1830 and 1850 by the Belgian polymath Adolphe Quetelet during the course of developing 'social physics', it is defined as the individual's body mass divided by the square of their height – with the value universally being given in units of kg/m^2. (Wikipedia)

## How BMI Calculator shinyapp works

- App URL: https://nguyen-toan.shinyapps.io/PeerAssessment/

- Input your weight and height in either "kg & m" or "lb & in".

- Your result should appear immediately on the right of the site including the result of your health status.

## Reference

- The code is available at: 

  https://github.com/nguyen-toan/datasciencecoursera/tree/master/09_DevelopingDataProducts/PeerAssessment

