---
title       : Reproducible Research Quiz 1
subtitle    : (Use arrow keys to navigate)
author      : from Data Science Coursera
job         : 
framework   : io2012
highlighter : highlight.js
hitheme     : tomorrow
widgets     : [mathjax, quiz, boostrap]
mode        : selfcontained
url:
  lib: ../../libraries
  assets: ../../assets
--- &radio

## Question 1

Suppose I conduct a study and publish my findings. Which of the following is an example of a replication of my study?

1. An investigator at another institution conducts a study addressing the same question, collects her own data, analyzes it separately from me, and publishes her own findings.
2. _An investigator at another institution conducts a study addressing a different scientific question and publishes her findings._
3. I take my own data, analyze it again, and publish new findings.
4. I give my data to an independent investigator at another institution, she analyzes the data and gets the same results as I originally obtained.

--- &radio

## Question 2

Which of the following is a requirement for a published data analysis to be reproducible?

1. _The full computer code for doing the data analysis is made publicly available._
2. The investigator makes available his computer, on which the analysis was originally conducted.
3. The analysis is conducted on a variant of the Unix operating system.
4. The data analysis is conducted using R.

--- &radio

## Question 3

Which of the following is an example of a reproducible study?

1. The study's original authors re-run their computer code on their analytic data and confirm publicly that the findings match those of the published results.      
2. The study's analytic data are publicly available, but the computer code is not.			
3. _The study's analytic data and computer code for the data analysis are publicly available. When the code is run on the analytic data, the findings are identical to the published results._
4. The study's analytic data and computer code are not publicly available, but the study was simple enough to be repeated by an independent investigator.

--- &radio

## Question 4

Which of the following is a reason that a study might NOT be fully replicated?

1. The original study was published in a high impact journal and is considered authoritative.    	
2. The original investigator does not want to make the analytic data available.			
3. _The original study was very expensive and there is no money to repeat it in a different setting._
4. The original study was conducted by a well-known investigator.

--- &radio

## Question 5

Which of the following is a reason why publishing **reproducible research** is increasingly important?

1. Most studies today are small-scale and easily replicated.    	
2. Computing power is limited today, making it difficult to apply sophisticated statistical methods.			
3. _New technologies are increasing the rate of data collection, creating datasets that are more complex and extremely high dimensional._
4. The statistical methods for most studies can be accurately described using plain language.

--- &radio

## Question 6

What is the role of *processing code* in the research pipeline?

1. _It transforms the measured data into analytic data._
2. It transforms the computational results into figures and tables.  		
3. It transforms the analytic data into computational results.			
4. It conducts the statistical analysis of the primary outcome.

--- &radio

## Question 7

Which is a goal of literate statistical programming?

1. _Combine explanatory text and data analysis code in a single document._
2. Require that data analysis summaries are always written in LaTeX.			
3. Ensure that data analysis documents are always exported in PDF format.			
4. Separate figures and tables from other data analytic summaries.

--- &radio

## Question 8

What does it mean to weave a literate statistical program?

1. Transform the literate program into a machine readable code file.    	
2. Transform a literate program from R to python.			
3. Compress the literate program so that it takes up less space.			
4. _Transform the literate program into a human readable document._

--- &radio

## Question 9

Which of the following is required to implement a literate programming system?

1. A Unix-based computer system.    	
2. A web server for publishing documents.			
3. _A documentation language like LaTeX._
4. A cloud-based computing service for running computations.

--- &radio

## Question 10

What is one way in which the knitr system differs from Sweave?

1. knitr was developed by Friedrich Leisch.    	
2. _knitr allows for the use of markdown instead of LaTeX._
3. knitr is written in python instead of R.
4. knitr lacks features like caching of code chunks.
